In [78]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [79]:
df = pd.read_csv("deep_insurance.txt")
df.head()

,age,affordability,bought_insurance
0,22,0.63,0
1,25,0.81,0
2,47,0.35,1
3,52,0.42,0
4,46,0.78,1


In [80]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df[['age','affordability']],df.bought_insurance,test_size = 0.2,random_state = 25)

In [81]:
len(x_train)

24

In [82]:
len(x_test)

6

In [83]:
x_train_scaled = x_train.copy()
x_train_scaled['age'] = x_train_scaled['age'] / 100 # Because the age is between 1 to 100

x_test_scaled = x_test.copy()
x_test_scaled['age'] = x_test_scaled['age'] / 100

In [84]:
x_train_scaled

,age,affordability
10,0.18,0.91
14,0.49,0.68
0,0.22,0.63
6,0.55,0.77
25,0.54,0.66
13,0.29,0.51
21,0.26,0.98
16,0.25,0.45
17,0.58,0.71
28,0.35,0.80


In [ ]:
model = keras.Sequential([
    keras.layers.Dense(1,input_shape = (2,),activation = 'sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(x_train_scaled,y_train,epochs = 5000)

Epoch 1/5000


C:\Users\avraj\AppData\Roaming\Python\Python313\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 425ms/step - accuracy: 0.5000 - loss: 0.7398
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7395
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7391
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.7387
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7383
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.7379
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.7375
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7371
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7367
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7363
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7359
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - lo

In [88]:
model.evaluate(x_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 1.0000 - loss: 0.4209


[0.42090216279029846, 1.0]

In [89]:
x_test_scaled

,age,affordability
19,0.18,0.52
11,0.28,0.85
2,0.47,0.35
9,0.61,0.59
24,0.50,0.74
27,0.30,0.69


In [90]:
model.predict(x_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


array([[0.21790537],
       [0.42473283],
       [0.5477929 ],
       [0.78396225],
       [0.69727963],
       [0.40600935]], dtype=float32)

In [91]:
y_test

19    0
11    0
2     1
9     1
24    1
27    0
Name: bought_insurance, dtype: int64

In [92]:
coef,intercept = model.get_weights()
coef,intercept

(array([[5.773413 ],
        [1.2036334]], dtype=float32),
 array([-2.9430184], dtype=float32))

In [93]:
def sigmoid(x):
    import math
    return 1 / (1+math.exp(-x))
sigmoid(18)

0.9999999847700205

In [94]:
def prediction_function(age,affordability):
    weighted_sum = coef[0]*age + coef[1]*affordability + intercept
    return sigmoid(weighted_sum)

In [95]:
prediction_function(.47,1)

C:\Users\avraj\AppData\Local\Temp\ipykernel_31784\3479825010.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1+math.exp(-x))


0.7259397772021446

In [96]:
def log_loss(y_true,y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [max(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new) + (1-y_true)*np.log(1-y_predicted_new))
    

In [97]:
def sigmoid_numpy(x):
    return 1 / (1+np.exp(-x))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [98]:
def gradient_descent(age,affordability,y_true,epochs,loss_thresold):
    #w1 , w2 , bias
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)

    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)

        loss = log_loss(y_true,y_predicted)

        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
        w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true))

        bias_d = np.mean(y_predicted-y_true)

        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d

        print(f"Epoch:{i},w1:{w1},w2:{w2},bias:{bias},loss:{loss}")

        if loss<=loss_thresold:
            break

    return w1 , w2 , bias

In [76]:
gradient_descent(x_train_scaled['age'],x_train_scaled['affordability'],y_train,1000, 0.7057)

Epoch:0,w1:0.9827073852295546,w2:0.9353476926419264,bias:-0.1157660021747731,loss:17.26978799617044
Epoch:1,w1:0.9716852097840707,w2:0.8808509795010323,bias:-0.21526056940632476,loss:17.26978799617044
Epoch:2,w1:0.96631501973388,w2:0.8355310703170917,bias:-0.30011922076900693,loss:17.26978799617044
Epoch:3,w1:0.965890424139119,w2:0.7982609776501282,bias:-0.37218523240887347,loss:17.26978799617044
Epoch:4,w1:0.9696956259125107,w2:0.7678938923907432,bias:-0.4333110910950285,loss:17.26978799617044
Epoch:5,w1:0.977056973620723,w2:0.7433479245018444,bias:-0.48523034469925097,loss:17.26978799617044
Epoch:6,w1:0.9873703699911953,w2:0.7236514956939896,bias:-0.529491134507635,loss:17.26978799617044
Epoch:7,w1:1.0001113291122454,w2:0.7079603353547339,bias:-0.5674333969275329,loss:17.26978799617044
Epoch:8,w1:1.014834360124366,w2:0.695556951470247,bias:-0.6001925365502376,loss:17.26978799617044
Epoch:9,w1:1.0311666976991605,w2:0.6858407819855592,bias:-0.6287168472047892,loss:17.26978799617044
Epo

(np.float64(11.664677572607788),
 np.float64(2.845622893641206),
 np.float64(-6.350104999512562))

In [99]:
coef,intercept

(array([[5.773413 ],
        [1.2036334]], dtype=float32),
 array([-2.9430184], dtype=float32))

In [ ]:
w1 = 5.06087 , w2 = 1.4086502 , bias = -2.9137027